language: ruby
rvm:
  - 2.0.0
install:
  - sudo apt-get update -y
  - sudo apt-get dist-upgrade -y
  - sudo apt-get install -y virtualbox --fix-missing # Everything falls apart here exactly.
  - sudo wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
script:
  - sudo vagrant up # The error is only presented when executing vagrant up
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
