language: ruby
rvm:
  - 1.9.3
install:
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - sudo apt-get install -q virtualbox --fix-missing # Everything falls apart here exactly.
  - sudo wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
script:
  - sudo vagrant up # The error is only presented when executing vagrant up
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
