language: ruby
rvm:
  - 2.0.0
install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - echo "deb http://download.openvz.org/debian wheezy main" | sudo tee /etc/apt/sources.list.d/openvz-rhel6.list
  - wget http://ftp.openvz.org/debian/archive.key
  - sudo apt-key add archive.key
  - sudo apt-get update
  - sudo apt-get -y install inux-headers-2.6.32-openvz-042stab094.7-amd64
  - sudo apt-get -y install virtualbox-4.3
  - sudo dpkg-reconfigure virtualbox-4.3
  - sudo modprobe vboxdrv
  - VBoxManage -v
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
script:
  - /opt/vagrant/bin/vagrant up
  - ls
  - /opt/vagrant/bin/vagrant ssh --command "touch /vagrant/smash_it_with_a_hammer"
  - ls